// copilot

const menuArray = {
  classic_ItalianMeatballs: 'Classic Italian Meatballs: Tender beef and pork meatballs simmered in a rich marinara sauce, served over a bed of al dente spaghetti. Perfect for those craving a traditional Italian experience.',

  turkeyMeatballs: 'Turkey Meatballs with Romesco Sauce: Healthy and flavorful turkey meatballs served with a nutty, roasted red pepper Romesco sauce. A great option for those looking for a lighter alternative.',

  lambMeatballs: 'Lamb Meatballs with Pecan Romesco: Juicy lamb meatballs filled with gooey cheese and bathed in a creamy pecan Romesco sauce. A hearty and indulgent choice for meat lovers.',

  coconutCurryMeatballs: 'Coconut Curry Meatballs: Aromatic meatballs cooked in a creamy coconut curry sauce, infused with spices and herbs. Ideal for those who enjoy a bit of heat and exotic flavors.',

  meatballSubSandwich: 'Meatball Sub Sandwich: Soft, freshly baked bread filled with savory meatballs, melted cheese, and a tangy marinara sauce. A satisfying and portable meal for a quick lunch or dinner.'

}

const source = document.createElement('div')
source.id = 'menu-info';

source.innerText = 'The text above is generated by windows copilot.';

export function activateMenu(content) {
  const menu = document.createElement('ul');

  for (const [key, value] of Object.entries(menuArray)) {
    const valueSplitted = value.split(':');
  
    const menuItem = document.createElement('li');
    menuItem.innerHTML = `<span class='menu-name'>${valueSplitted[0]}:</span> ${valueSplitted[1]}`;
    
    menuItem.setAttribute('id', key);
    
    menu.appendChild(menuItem);
  }

  content.appendChild(menu);
  
  content.appendChild(source);
}
